config/routes.rb
Rails.application.routes.draw do

  root 'pastes#new'
  resources :pastes

  

end

app/models/paste.rb
class Paste < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pastes_controller.rb
class PastesController < ApplicationController
    def index
        @pastes = Paste.all.order("created_at DESC")
    end
    
    def new
        @paste = Paste.new
    end
    
    def create
        @paste = Paste.new(paste_params)
        
        if @paste.title == ""
            @paste.title = "Untitled"
        end
        
        if @paste.save
            redirect_to Paste.last
        else
            render 'new'
        end
        
    end
    
    def show
        @paste = Paste.find(params[:id])
    end
    
    private
    
        def paste_params
            params.require(:paste).permit(:title, :description)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pastes_helper.rb
module PastesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snippet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <style>

  </style>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
    </ul>
    <%= link_to "+ new paste", new_paste_path, :class => "btn btn-success navbar-btn" %>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/pastes/_form.html.erb
<div class="container-fluid">
        <%= simple_form_for @paste do |f| %>
        <%= f.input :description %><br>
          <%= f.input :title, label: "Paste Name / Title" %>
          <%= f.button :submit, class: 'btn btn-default' %>
        <% end %>
</div>

app/views/pastes/index.html.erb
<!--<% @pastes.each do |paste| %>
    <h2><%= paste.title %></h2>
    <%= link_to "View Snippet", paste_path(paste), class: "btn btn-default" %>
<% end %>
-->

app/views/pastes/new.html.erb
    <div class="col-md-6" >

      <%= render 'form' %>

    </div>

app/views/pastes/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= @paste.title %></div>
  <div class="panel-body">
    <pre><%= @paste.description %></pre>
  </div>
</div>